[tool.ruff]
line-length = 120

exclude = [
    ".git",
    ".ruff_cache",
    "__pycache__",
    "*/migrations/*",
    ".venv",
    "venv",
]

[tool.ruff.lint]
select = ["E", "F", "I", "N", "UP", "S", "B", "C4", "T20", "Q", "RET", "SIM", "PTH"]
ignore = ["S101"]

[tool.ruff.lint.flake8-quotes]
docstring-quotes = "double"
inline-quotes = "single"

[tool.ruff.lint.isort]
known-first-party = ["where_from"]

[tool.ruff.lint.pydocstyle]
convention = "google"