# Generated by Django 5.2.1 on 2025-05-21 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('common_name', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.TextField(blank=True, null=True)),
                ('independent', models.BooleanField(default=True)),
                ('google_maps', models.URLField(blank=True, max_length=500, null=True)),
                ('open_street_maps', models.URLField(blank=True, max_length=500, null=True)),
                ('capital', models.TextField(blank=True, null=True)),
                ('capital_coordinates', models.TextField(blank=True, null=True)),
                ('flags', models.URLField(blank=True, max_length=500, null=True)),
                ('flags_svg', models.URLField(blank=True, max_length=500, null=True)),
                ('flaf_alt', models.TextField(blank=True, null=True)),
                ('coat_of_arms_png', models.URLField(blank=True, max_length=500, null=True)),
                ('coat_of_arms_svg', models.URLField(blank=True, max_length=500, null=True)),
                ('borders_with', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('count_of_reguests', models.IntegerField(default=1)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NameCountryProbability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probability', models.FloatField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='names.country')),
                ('name_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='names.name')),
            ],
            options={
                'unique_together': {('name_request', 'country')},
            },
        ),
    ]
